### DISCUSSION TITLE
Getting custom link icons to show

### DISCUSSION THREAD

**Discussion by tf13** [imdone/imdone#69] [Q&A]
Do I have to do something to get Font Awesome icons, specified in a board's config.yml file, to appear at the top of cards in imdone? I feel like I got this to work the last time I tried the app a while ago, but now the icons aren't showing up, even though the links are working. 

Here's an example, which does the same thing no matter what I use — except that `pack: fab` with `icon:twitter` works (as do the built-in examples, `pack: fas` with `icon: filter` and `pack: fab` with `icon: github`):

```
  cards:
    colors:
      - color: green
        filter: context=work&context=wsj
    links:
      - href: 'file://${source.repoId}'
        icon: skull
        pack: fas
        title: '${source.repoId}'
```

Result (with pointer hovering over where the icon should be — that blank spot at the top, far right corner of the card):

<img width="309" alt="image" src="https://user-images.githubusercontent.com/16142258/111034415-89f0b300-83e3-11eb-9cb9-ab2a7bc01260.png">
