### ISSUE TITLE
Define target on filtered lists

### ISSUE THREAD

**Issue by telenieko** [imdone/imdone#35]
Hi,

A thing I do is have my DONE list setup like that:

```yaml
lists:
  - name: TODO
    hidden: false
    ignore: false
  - name: DONE (recent)
    hidden: false
    filter: 'completedDate > "${7 days ago}" AND list = DONE'
```

That removes a lot of noise from the DONE list by only showing last week's cards.

But this breaks the drag&drop workflow because you cannot drop cards into filtered lists.

The request here is to be able to tell imdone what should happen when an item is dropped into a filtered list.

```yaml
lists:
  -name: DONE (recent)
    hidden: false
    filter: 'completedDate > "${7 days ago}" AND list = DONE'
    on_drop: list = DONE
```

The schemantics of `on_drop` could be similar to `patch` in #34 thus that would not be limited to moving from list to list, while the syntax for the most simple use case is quite short.
