### ISSUE TITLE
Handling of metadata data types

### ISSUE THREAD

**Issue by telenieko** [imdone/imdone#39]
Hi!

It is currently not possible to treat metadata as anything else than a string as far as I've seen, so this is not possible:

```html
<!-- #TODO: Renew password soon
due:2021-06-30 defer:2021-05-01
My passport is due soon, renewal has to occur withing 90 days
---> 
```

and in `config.yml`

```yaml
- name: TODO (available)
    hidden: false
    ignore: false
    filter: defer = null OR defer < tomorrow
```

The use case is clear: avoid cluttering the task lists with tasks you cannot deal with because of their dates.

A possible syntax could be:

```yaml
- name: TODO (available)
    hidden: false
    ignore: false
    filter: defer = null OR date(defer) < tomorrow
```

That is: have helper functions to tell `imdone` what the type of the metadata field should be so it can be used that way (instead of guessing the type, which could lead to unexpected results). Other candidates could be `int()`, etc.
